# Generated by Django 2.1.4 on 2018-12-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('listado_docuemento', models.IntegerField()),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
